spring:
  application:
    name: java_crud
  datasource:
#    url: jdbc:postgresql://34.203.214.109:5432/jwt_security
#    username: postgres
#    password: amigosIsNigger
    url: jdbc:postgresql://localhost:5432/java_crud
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect